allowBuilds:
  '@swc/core': true
  better-sqlite3: true
  ffmpeg-static: true
  protobufjs: true
  puppeteer: true

ignoredBuiltDependencies:
  - puppeteer

onlyBuiltDependencies:
  - "@swc/core"
  - better-sqlite3
  - ffmpeg-static
  - protobufjs
  - unrs-resolver
